#pragma once

#include "CommonConfig.h"

[System::FlagsAttribute]
public enum class NinCFGFlags {
	CHEATS = NIN_CFG_CHEATS,
	DEBUGGER = NIN_CFG_DEBUGGER,
	DEBUGWAIT = NIN_CFG_DEBUGWAIT,
	MEMCARDEMU = NIN_CFG_MEMCARDEMU,
	CHEAT_PATH = NIN_CFG_CHEAT_PATH,
	FORCE_WIDE = NIN_CFG_FORCE_WIDE,
	FORCE_PROG = NIN_CFG_FORCE_PROG,
	AUTO_BOOT = NIN_CFG_AUTO_BOOT,
	REMLIMIT = NIN_CFG_REMLIMIT,
	OSREPORT = NIN_CFG_OSREPORT,
	USB = NIN_CFG_USB,
	LED = NIN_CFG_LED,
	LOG = NIN_CFG_LOG,
	MC_MULTI = NIN_CFG_MC_MULTI,
	NATIVE_SI = NIN_CFG_NATIVE_SI,
	WIIU_WIDE = NIN_CFG_WIIU_WIDE,
	ARCADE_MODE = NIN_CFG_ARCADE_MODE,
	CC_RUMBLE = NIN_CFG_CC_RUMBLE,
	SKIP_IPL = NIN_CFG_SKIP_IPL,
	BBA_EMU = NIN_CFG_BBA_EMU,
	MC_SLOTB = NIN_CFG_MC_SLOTB,
};

public enum class NinCFGLanguage {
	ENGLISH = NIN_LAN_ENGLISH,
	GERMAN = NIN_LAN_GERMAN,
	FRENCH = NIN_LAN_FRENCH,
	SPANISH = NIN_LAN_SPANISH,
	ITALIAN = NIN_LAN_ITALIAN,
	DUTCH = NIN_LAN_DUTCH,
	FIRST = NIN_LAN_FIRST,
	LAST = NIN_LAN_LAST,
	AUTO = NIN_LAN_AUTO,
};

public enum class NinCFGVideoMode {
	AUTO = NIN_VID_AUTO,
	FORCE = NIN_VID_FORCE,
	NONE = NIN_VID_NONE,
	FORCE_DF = NIN_VID_FORCE_DF,
};

public enum class NinCFGForcedVideoMode {
	NONE = 0,
	PAL50 = NIN_VID_FORCE_PAL50,
	PAL60 = NIN_VID_FORCE_PAL60,
	NTSC = NIN_VID_FORCE_NTSC,
	MPAL = NIN_VID_FORCE_MPAL,
};
