#pragma once

#include "CommonConfig.h"

public enum class NinCFGLanguage {
	ENGLISH = NIN_LAN_ENGLISH,
	GERMAN = NIN_LAN_GERMAN,
	FRENCH = NIN_LAN_FRENCH,
	SPANISH = NIN_LAN_SPANISH,
	ITALIAN = NIN_LAN_ITALIAN,
	DUTCH = NIN_LAN_DUTCH,
	FIRST = NIN_LAN_FIRST,
	LAST = NIN_LAN_LAST,
	AUTO = NIN_LAN_AUTO,
};

public enum class NinCFGVideoMode {
	AUTO = NIN_VID_AUTO,
	FORCE = NIN_VID_FORCE,
	NONE = NIN_VID_NONE,
	FORCE_DF = NIN_VID_FORCE_DF,
};

public enum class NinCFGForcedVideoMode {
	NONE = 0,
	PAL50 = NIN_VID_FORCE_PAL50,
	PAL60 = NIN_VID_FORCE_PAL60,
	NTSC = NIN_VID_FORCE_NTSC,
	MPAL = NIN_VID_FORCE_MPAL,
};
